name: Python TestNG Style Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Manual trigger support

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        make install

    - name: Run Tests
      run: |
        make test

    - name: Generate HTML Report
      run: |
        mkdir -p reports
        make report

    - name: Archive Test Report (Artifacts)
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report
        path: reports/report.html
