# .github/workflows/test.yml
name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run tests and generate HTML report
        run: |
          mkdir -p reports
          pytest --html=reports/index.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/
